// Browser-side export helpers: CSV (Excel-compatible), printable HTML, and a simple PDF via window.print.
import { formatCurrency, formatDate } from './formatters';
import { CURRENCY_SYMBOLS } from './constants';

export function exportTransactionsCSV(transactions, currency, filename = 'transactions.csv') {
  const headers = ['Title', 'Type', 'Category', 'Amount', 'Date', 'Notes'];
  const rows = transactions.map((t) => [
    escapeCSV(t.title),
    t.type,
    t.category,
    t.amount,
    formatDate(t.date),
    escapeCSV(t.notes || ''),
  ]);
  const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  downloadBlob(filename, csv, 'text/csv;charset=utf-8;');
}

function escapeCSV(v) {
  if (v == null) return '';
  const s = String(v);
  if (s.includes(',') || s.includes('"') || s.includes('\n')) return `"${s.replace(/"/g, '""')}"`;
  return s;
}

function downloadBlob(filename, content, type) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportReportPDF(report) {
  // We open a print-optimized window; the user can "Save as PDF" from the print dialog.
  const win = window.open('', '_blank', 'width=900,height=700');
  if (!win) return;
  const symbol = CURRENCY_SYMBOLS[report.currency] || '₹';
  const rows = report.transactions.map((t) => `
    <tr>
      <td>${escapeHtml(t.title)}</td>
      <td>${t.type}</td>
      <td>${t.category}</td>
      <td style="text-align:right">${symbol}${Number(t.amount).toLocaleString('en-IN')}</td>
      <td>${formatDate(t.date)}</td>
      <td>${escapeHtml(t.notes || '')}</td>
    </tr>`).join('');

  win.document.write(`<!doctype html>
  <html><head><title>${escapeHtml(report.title)}</title>
  <style>
    * { font-family: 'Inter', system-ui, sans-serif; }
    body { padding: 40px; color: #1a1d24; }
    h1 { font-size: 24px; margin: 0 0 4px; }
    .meta { color: #6e7587; font-size: 13px; margin-bottom: 24px; }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 24px; }
    .stat { border: 1px solid #eef0f4; border-radius: 12px; padding: 12px 16px; }
    .stat .label { font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #6e7587; }
    .stat .value { font-size: 18px; font-weight: 700; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { text-align: left; padding: 10px 12px; background: #f7f8fa; border-bottom: 1px solid #eef0f4; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; color: #6e7587; }
    td { padding: 10px 12px; border-bottom: 1px solid #f0f2f5; }
    .income { color: #059669; font-weight: 600; }
    .expense { color: #e11d48; font-weight: 600; }
    footer { margin-top: 32px; color: #9aa1b3; font-size: 11px; text-align: center; }
    @media print { body { padding: 0; } }
  </style></head>
  <body>
    <h1>${escapeHtml(report.title)}</h1>
    <div class="meta">${escapeHtml(report.subtitle)} · Generated ${new Date().toLocaleString()}</div>
    <div class="stats">
      <div class="stat"><div class="label">Income</div><div class="value income">${symbol}${report.income.toLocaleString('en-IN')}</div></div>
      <div class="stat"><div class="label">Expense</div><div class="value expense">${symbol}${report.expense.toLocaleString('en-IN')}</div></div>
      <div class="stat"><div class="label">Net</div><div class="value">${symbol}${report.net.toLocaleString('en-IN')}</div></div>
      <div class="stat"><div class="label">Transactions</div><div class="value">${report.transactions.length}</div></div>
    </div>
    <table>
      <thead><tr><th>Title</th><th>Type</th><th>Category</th><th style="text-align:right">Amount</th><th>Date</th><th>Notes</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
    <footer>Generated by FinTrack · Expense Tracker & Analytics</footer>
    <script>window.onload = () => { setTimeout(() => window.print(), 300); }</script>
  </body></html>`);
  win.document.close();
}

export function printReport(report) {
  exportReportPDF(report);
}

function escapeHtml(s) {
  return String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}
